// Government schemes data
const schemes = [
    {
        id: 'pmkisan',
        name: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
        description: 'Income support scheme for farmers',
        eligibility: 'Small and marginal farmers with landholding up to 2 hectares',
        benefits: '₹6,000 per year in three equal installments',
        documents: 'Aadhaar card, Land records, Bank account details',
        deadline: 'Ongoing',
        link: 'https://pmkisan.gov.in/',
        guide: '<ol><li>Visit the PM-KISAN portal</li><li>Click on "New Farmer Registration"</li><li>Fill in your details and upload documents</li><li>Submit the form</li><li>Check status using your Aadhaar number</li></ol>',
        sector: 'Agriculture',
        businessType: ['Agri'],
        size: ['Micro', 'Small'],
        location: ['Delhi', 'Rural', 'North'],
        revenue: ['Low', 'Medium'],
        years: ['1-3', '3-5', '5+'],
        detailedDescription: 'PM-KISAN is a Central Sector Scheme with 100% funding from Government of India. The scheme aims to supplement the financial needs of all landholding farmers\' families in procuring various inputs to ensure proper crop health and appropriate yields, commensurate with the anticipated farm income.'
    },
    {
        id: 'pmfme',
        name: 'Pradhan Mantri Formalisation of Micro Food Processing Enterprises (PMFME)',
        description: 'Scheme for micro food processing units',
        eligibility: 'Micro enterprises, SHGs, FPOs in food processing sector',
        benefits: '35% capital subsidy up to ₹10 lakh, credit linked subsidy',
        documents: 'Aadhaar, PAN, Business registration, Project report',
        deadline: 'March 2025',
        link: 'https://pmfme.mofpi.gov.in/',
        guide: '<ol><li>Register on PMFME portal</li><li>Complete the eligibility test</li><li>Prepare a detailed project report</li><li>Submit application with required documents</li><li>Await approval and disbursement</li></ol>',
        sector: 'Food Processing',
        businessType: ['Agri', 'MSME', 'Women'],
        size: ['Micro'],
        location: ['Delhi', 'Rural', 'Urban'],
        revenue: ['Low', 'Medium'],
        years: ['New', '1-3', '3-5'],
        detailedDescription: 'The PMFME scheme aims to enhance the competitiveness of existing individual micro-enterprises in the unorganized segment of the food processing industry and promote formalization of the sector. It provides financial, technical, and business support for upgradation of micro food processing enterprises.'
    },
    {
        id: 'udyam',
        name: 'Udyam Registration',
        description: 'MSME registration for benefits and subsidies',
        eligibility: 'Micro, Small and Medium Enterprises as per investment and turnover criteria',
        benefits: 'Access to all MSME schemes, lower interest rates, tax benefits',
        documents: 'Aadhaar, PAN, Business address proof',
        deadline: 'Ongoing',
        link: 'https://udyamregistration.gov.in/',
        guide: '<ol><li>Visit Udyam Registration portal</li><li>Enter Aadhaar and PAN details</li><li>Fill business information</li><li>Submit self-declaration</li><li>Download registration certificate</li></ol>',
        sector: 'All',
        businessType: ['MSME', 'Startup', 'Women', 'SCST'],
        size: ['Micro', 'Small', 'Medium'],
        location: ['Delhi', 'Rural', 'Urban', 'North', 'South', 'East', 'West', 'Northeast'],
        revenue: ['Low', 'Medium', 'High'],
        years: ['New', '1-3', '3-5', '5+'],
        detailedDescription: 'Udyam Registration is a government registration for Micro, Small and Medium Enterprises (MSMEs) that replaces the earlier system of MSME registration. It provides a permanent registration number and certificate that helps businesses avail various benefits, subsidies and schemes offered by the government.'
    },
    {
        id: 'standup',
        name: 'Stand-Up India',
        description: 'Loan scheme for SC/ST and women entrepreneurs',
        eligibility: 'SC/ST and women entrepreneurs for greenfield projects',
        benefits: 'Bank loan from ₹10 lakh to ₹1 crore for enterprise setup',
        documents: 'Caste certificate (if applicable), Project report, KYC documents',
        deadline: 'Ongoing',
        link: 'https://www.standupmitra.in/',
        guide: '<ol><li>Identify a bank branch that handles Stand-Up India loans</li><li>Prepare a detailed project report</li><li>Submit application with required documents</li><li>Attend interview if required</li><li>Await loan sanction and disbursement</li></ol>',
        sector: 'All',
        businessType: ['Women', 'SCST'],
        size: ['Micro', 'Small'],
        location: ['Delhi', 'Rural', 'Urban'],
        revenue: ['Low', 'Medium'],
        years: ['New'],
        detailedDescription: 'Stand-Up India scheme facilitates bank loans between ₹10 lakh and ₹1 crore to at least one Scheduled Caste (SC) or Scheduled Tribe (ST) borrower and at least one woman borrower per bank branch for setting up a greenfield enterprise in manufacturing, services or the trading sector.'
    },
    {
        id: 'mudra',
        name: 'Pradhan Mantri MUDRA Yojana (PMMY)',
        description: 'Loan scheme for micro businesses',
        eligibility: 'Non-corporate, non-farm small/micro enterprises',
        benefits: 'Loans up to ₹10 lakh under three categories: Shishu, Kishor, Tarun',
        documents: 'Aadhaar, PAN, Business proof (if existing), Project report',
        deadline: 'Ongoing',
        link: 'https://www.mudra.org.in/',
        guide: '<ol><li>Visit any bank/NBFC/MFI that offers MUDRA loans</li><li>Choose appropriate loan category</li><li>Submit application with required documents</li><li>Provide collateral if required (for loans above ₹50,000)</li><li>Await loan approval</li></ol>',
        sector: 'All',
        businessType: ['MSME', 'Women', 'SCST'],
        size: ['Micro'],
        location: ['Delhi', 'Rural', 'Urban'],
        revenue: ['Low', 'Medium'],
        years: ['New', '1-3'],
        detailedDescription: 'The Pradhan Mantri MUDRA Yojana (PMMY) provides loans up to ₹10 lakh to non-corporate, non-farm small/micro enterprises. These loans are classified as MUDRA loans under PMMY and are provided by Commercial Banks, RRBs, Small Finance Banks, MFIs and NBFCs.'
    },
    {
        id: 'cgtmse',
        name: 'Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE)',
        description: 'Collateral-free loans for MSMEs',
        eligibility: 'Micro and small enterprises in manufacturing and service sectors',
        benefits: 'Collateral-free loans up to ₹2 crore, guarantee cover up to 85%',
        documents: 'KYC documents, Business proof, Financial statements',
        deadline: 'Ongoing',
        link: 'https://www.cgtmse.in/',
        guide: '<ol><li>Approach a member lending institution (MLI)</li><li>Submit loan application along with CGTMSE application</li><li>Provide required business and financial documents</li><li>Pay guarantee fee (0.75-1.5% of loan amount)</li><li>Await loan approval with guarantee cover</li></ol>',
        sector: 'All',
        businessType: ['MSME', 'Women', 'SCST'],
        size: ['Micro', 'Small'],
        location: ['Delhi', 'Rural', 'Urban'],
        revenue: ['Low', 'Medium', 'High'],
        years: ['1-3', '3-5', '5+'],
        detailedDescription: 'CGTMSE scheme provides collateral-free credit to micro and small enterprises (MSEs) for loans up to ₹2 crore. The trust provides guarantee cover up to 85% of the sanctioned credit facility, encouraging banks to provide loans without collateral security.'
    },
    {
        id: 'psu',
        name: 'Public Procurement Policy for MSEs',
        description: 'Mandatory procurement from MSEs by PSUs',
        eligibility: 'All registered MSEs, with special provisions for SC/ST and women-owned',
        benefits: '20% mandatory procurement by PSUs from MSEs, 4% from SC/ST and 3% from women-owned MSEs',
        documents: 'Udyam Registration, Additional registration on GeM portal',
        deadline: 'Ongoing',
        link: 'https://msme.gov.in/public-procurement-policy-mse-sector-2018',
        guide: '<ol><li>Register on Government e-Marketplace (GeM) portal</li><li>Complete vendor registration process</li><li>List your products/services with proper categorization</li><li>Bid for tenders as per eligibility</li><li>Maintain quality and delivery standards</li></ol>',
        sector: 'All',
        businessType: ['MSME', 'Women', 'SCST'],
        size: ['Micro', 'Small'],
        location: ['Delhi', 'Rural', 'Urban'],
        revenue: ['Low', 'Medium', 'High'],
        years: ['1-3', '3-5', '5+'],
        detailedDescription: 'The Public Procurement Policy mandates that all Central Government Ministries, Departments and Public Sector Undertakings procure minimum 20% of their annual value of goods/services from Micro and Small Enterprises (MSEs), with sub-targets of 4% for MSEs owned by SC/ST entrepreneurs and 3% for MSEs owned by women entrepreneurs.'
    },
    {
        id: 'zedsanction',
        name: 'ZED Certification Scheme',
        description: 'Quality certification for MSMEs',
        eligibility: 'Manufacturing MSMEs registered with Udyam',
        benefits: 'Subsidy up to 80% on certification fees, improved quality and competitiveness',
        documents: 'Udyam certificate, Factory documents, Quality policy',
        deadline: 'March 2025',
        link: 'https://zed.org.in/',
        guide: '<ol><li>Register on ZED portal</li><li>Complete self-assessment</li><li>Choose appropriate certification level (Bronze, Silver, Gold, Diamond, Platinum)</li><li>Undergo assessment by ZED Maturity Assessment Cell</li><li>Implement suggestions and get certified</li></ol>',
        sector: 'Manufacturing',
        businessType: ['MSME', 'Women', 'SCST'],
        size: ['Micro', 'Small', 'Medium'],
        location: ['Delhi', 'Rural', 'Urban'],
        revenue: ['Medium', 'High'],
        years: ['3-5', '5+'],
        detailedDescription: 'Zero Defect Zero Effect (ZED) certification scheme aims to rate and handhold all MSMEs to deliver top quality products with minimal environmental impact. The scheme provides subsidy for certification costs and helps MSMEs improve their quality standards to compete in global markets.'
    },
    {
        id: 'scsthub',
        name: 'SC/ST Hub Scheme',
        description: 'Support for SC/ST entrepreneurs',
        eligibility: 'SC/ST owned MSMEs registered with Udyam',
        benefits: 'Subsidy up to ₹15 lakh, special tenders, capacity building',
        documents: 'Caste certificate, Udyam registration, Business proof',
        deadline: 'March 2025',
        link: 'https://scsthub.in/',
        guide: '<ol><li>Register on SC/ST Hub portal</li><li>Complete profile with business details</li><li>Apply for relevant schemes/tenders</li><li>Participate in capacity building programs</li><li>Avail financial and technical support</li></ol>',
        sector: 'All',
        businessType: ['SCST'],
        size: ['Micro', 'Small', 'Medium'],
        location: ['Delhi', 'Rural', 'Urban'],
        revenue: ['Low', 'Medium', 'High'],
        years: ['New', '1-3', '3-5', '5+'],
        detailedDescription: 'The SC/ST Hub scheme provides comprehensive support to Scheduled Caste and Scheduled Tribe entrepreneurs to effectively participate in public procurement. It includes financial assistance, capacity building, special procurement preferences and handholding support to help SC/ST entrepreneurs grow their businesses.'
    },
    {
        id: 'womentech',
        name: 'Women Entrepreneurship Platform (WEP)',
        description: 'Support platform for women entrepreneurs',
        eligibility: 'Women-owned/led businesses across sectors',
        benefits: 'Mentorship, funding opportunities, incubation support',
        documents: 'Business registration, PAN, Aadhaar',
        deadline: 'Ongoing',
        link: 'https://wep.gov.in/',
        guide: '<ol><li>Register on WEP portal</li><li>Complete your business profile</li><li>Explore mentorship and funding opportunities</li><li>Participate in training programs</li><li>Connect with other women entrepreneurs</li></ol>',
        sector: 'All',
        businessType: ['Women'],
        size: ['Micro', 'Small', 'Medium'],
        location: ['Delhi', 'Rural', 'Urban'],
        revenue: ['Low', 'Medium', 'High'],
        years: ['New', '1-3', '3-5', '5+'],
        detailedDescription: 'The Women Entrepreneurship Platform (WEP) is a unified access portal that brings together women from different parts of India to realize their entrepreneurial aspirations. It provides information, funding, mentorship, incubation and acceleration support to women entrepreneurs across all stages of their journey.'
    },
    {
        id: 'agriinfra',
        name: 'Agriculture Infrastructure Fund (AIF)',
        description: 'Financing for post-harvest infrastructure',
        eligibility: 'Farmers, FPOs, Agri-entrepreneurs, startups in agriculture',
        benefits: '3% interest subvention up to ₹2 crore, credit guarantee up to ₹2 crore',
        documents: 'Land documents, Project report, KYC, Bank details',
        deadline: 'March 2027',
        link: 'https://agriinfra.dac.gov.in/',
        guide: '<ol><li>Identify eligible project (warehouse, cold storage, sorting/grading unit etc.)</li><li>Approach eligible lending institution</li><li>Submit application with project report</li><li>Get project appraised and sanctioned</li><li>Avail interest subvention during loan tenure</li></ol>',
        sector: 'Agriculture',
        businessType: ['Agri'],
        size: ['Micro', 'Small', 'Medium'],
        location: ['Delhi', 'Rural'],
        revenue: ['Low', 'Medium', 'High'],
        years: ['1-3', '3-5', '5+'],
        detailedDescription: 'The Agriculture Infrastructure Fund provides medium to long term debt financing for investment in viable projects for post-harvest management infrastructure and community farming assets through interest subvention and credit guarantee. The scheme aims to improve farm gate infrastructure and reduce post-harvest losses.'
    },
    {
        id: 'pmmsy',
        name: 'Pradhan Mantri Matsya Sampada Yojana (PMMSY)',
        description: 'Scheme for fisheries sector development',
        eligibility: 'Fishermen, fish farmers, FPOs, entrepreneurs in fisheries sector',
        benefits: 'Subsidy up to 40-60% of project cost depending on category',
        documents: 'Aadhaar, Fishery license, Land/water body documents, Project report',
        deadline: 'March 2025',
        link: 'https://pmmsy.dof.gov.in/',
        guide: '<ol><li>Identify eligible activity (fishing harbor, hatchery, cage culture etc.)</li><li>Submit application to State Fisheries Department</li><li>Get project appraised by technical committee</li><li>Implement project as per guidelines</li><li>Claim subsidy after completion</li></ol>',
        sector: 'Fisheries',
        businessType: ['Agri'],
        size: ['Micro', 'Small', 'Medium'],
        location: ['Delhi', 'Rural'],
        revenue: ['Low', 'Medium'],
        years: ['New', '1-3', '3-5'],
        detailedDescription: 'PMMSY aims to enhance fish production to 220 lakh metric tons by 2024-25, doubling exports to ₹1 lakh crore and generating about 55 lakh employment opportunities. The scheme focuses on sustainable development of fisheries sector with infrastructure modernization, value chain improvement and welfare of fishermen.'
    },
    {
        id: 'startupindia',
        name: 'Startup India Seed Fund Scheme',
        description: 'Funding for early-stage startups',
        eligibility: 'DPIIT recognized startups incorporated not more than 2 years ago',
        benefits: 'Up to ₹20 lakh as grant for proof of concept, up to ₹50 lakh as convertible debentures',
        documents: 'Startup recognition certificate, Pitch deck, Financial projections',
        deadline: 'March 2025',
        link: 'https://www.startupindia.gov.in/',
        guide: '<ol><li>Get DPIIT recognition for your startup</li><li>Identify an incubator supported under the scheme</li><li>Submit application through incubator</li><li>Present your idea to expert committee</li><li>Receive funding upon approval</li></ol>',
        sector: 'Technology',
        businessType: ['Startup'],
        size: ['Micro'],
        location: ['Delhi', 'Urban'],
        revenue: ['Low'],
        years: ['New', '1-3'],
        detailedDescription: 'The Startup India Seed Fund Scheme aims to provide financial assistance to startups for proof of concept, prototype development, product trials, market entry and commercialization. The scheme is implemented through eligible incubators across India who provide the funding to selected startups.'
    },
    {
        id: 'aspire',
        name: 'ASPIRE Scheme',
        description: 'Promotion of innovation and entrepreneurship in rural areas',
        eligibility: 'Entrepreneurs, startups, incubators in rural sectors',
        benefits: 'Funding support up to ₹50 lakh for incubators, up to ₹25 lakh for startups',
        documents: 'Business plan, Project report, Incubator agreement (if applicable)',
        deadline: 'March 2025',
        link: 'https://www.kviconline.gov.in/',
        guide: '<ol><li>Identify eligible rural sector (agri, food processing, rural crafts etc.)</li><li>Apply through Livelihood Business Incubator or directly for startup component</li><li>Present your idea to selection committee</li><li>Implement project with mentoring support</li><li>Avail funding as per milestones</li></ol>',
        sector: 'Agriculture',
        businessType: ['Startup', 'Agri'],
        size: ['Micro'],
        location: ['Rural'],
        revenue: ['Low'],
        years: ['New', '1-3'],
        detailedDescription: 'A Scheme for Promotion of Innovation, Rural Industry and Entrepreneurship (ASPIRE) aims to set up network of technology and incubation centers to accelerate entrepreneurship and promote startups for innovation in agro-based industry. It focuses on creating new jobs and reducing unemployment in rural areas.'
    },
    {
        id: 'meity',
        name: 'MeitY Startup Hub',
        description: 'Support for technology startups',
        eligibility: 'Tech startups in areas like IoT, AI, blockchain, robotics etc.',
        benefits: 'Funding up to ₹50 lakh, incubation support, mentorship',
        documents: 'Startup registration, Pitch deck, Technical documents',
        deadline: 'Ongoing',
        link: 'https://meitystartuphub.in/',
        guide: '<ol><li>Register on MeitY Startup Hub portal</li><li>Submit your startup details and pitch</li><li>Get evaluated by technical committee</li><li>Avail incubation space if selected</li><li>Receive funding support as per milestones</li></ol>',
        sector: 'Technology',
        businessType: ['Startup'],
        size: ['Micro'],
        location: ['Delhi', 'Urban'],
        revenue: ['Low'],
        years: ['New', '1-3'],
        detailedDescription: 'MeitY Startup Hub is a national platform that aims to nurture technology startups in emerging areas like Artificial Intelligence, Internet of Things, Blockchain, Robotics and other areas of electronics and IT. The hub provides funding, incubation, mentorship and market access support to selected startups.'
    },
    {
        id: 'nidhi',
        name: 'NIDHI-PRAYAS Program',
        description: 'Proof of concept funding for startups',
        eligibility: 'Individuals or startups with innovative ideas',
        benefits: 'Grant up to ₹10 lakh for prototype development',
        documents: 'Innovation details, Budget plan, Team information',
        deadline: 'Ongoing',
        link: 'https://www.nidhiprayas.gov.in/',
        guide: '<ol><li>Identify nearest PRAYAS center (hosted in incubators)</li><li>Submit application with innovation details</li><li>Present your idea to expert committee</li><li>Receive funding upon selection</li><li>Develop prototype within 18 months</li></ol>',
        sector: 'Technology',
        businessType: ['Startup'],
        size: ['Micro'],
        location: ['Delhi', 'Urban'],
        revenue: ['Low'],
        years: ['New'],
        detailedDescription: 'NIDHI-PRAYAS (Promoting and Accelerating Young and Aspiring Innovators & Startups) provides grant up to ₹10 lakh to individuals or startups to convert their innovative ideas into prototypes. The program aims to support innovators in the pre-incubation stage and help them validate their ideas.'
    },
    {
        id: 'geps',
        name: 'Government e-Marketplace (GeM) for MSEs',
        description: 'Platform for MSEs to sell to government',
        eligibility: 'All registered MSEs (Udyam registered preferred)',
        benefits: 'Direct access to government procurement, payment within 10 days',
        documents: 'Business registration, PAN, Bank details, Product certificates',
        deadline: 'Ongoing',
        link: 'https://gem.gov.in/',
        guide: '<ol><li>Register as seller on GeM portal</li><li>Complete vendor verification process</li><li>List your products/services with proper categorization</li><li>Bid for tenders as per eligibility</li><li>Fulfill orders with quality standards</li></ol>',
        sector: 'All',
        businessType: ['MSME', 'Women', 'SCST'],
        size: ['Micro', 'Small', 'Medium'],
        location: ['Delhi', 'Rural', 'Urban'],
        revenue: ['Low', 'Medium', 'High'],
        years: ['1-3', '3-5', '5+'],
        detailedDescription: 'Government e-Marketplace (GeM) is a one-stop portal to facilitate online procurement of common use goods and services required by various government departments and PSUs. MSEs get preference in government procurement through this platform with price and purchase preference benefits.'
    },
    {
        id: 'tread',
        name: 'Trade Related Entrepreneurship Assistance (TREAD)',
        description: 'Scheme for women entrepreneurs',
        eligibility: 'Women entrepreneurs in manufacturing or services',
        benefits: 'Up to 30% of project cost as government grant, remaining as loan',
        documents: 'Business plan, Project report, KYC documents',
        deadline: 'March 2025',
        link: 'https://msme.gov.in/',
        guide: '<ol><li>Identify eligible business activity</li><li>Approach designated lending institutions</li><li>Submit application with detailed project report</li><li>Get project appraised and approved</li><li>Avail grant portion after loan sanction</li></ol>',
        sector: 'All',
        businessType: ['Women'],
        size: ['Micro', 'Small'],
        location: ['Delhi', 'Rural', 'Urban'],
        revenue: ['Low', 'Medium'],
        years: ['New', '1-3'],
        detailedDescription: 'TREAD scheme aims to empower women entrepreneurs by providing credit and non-credit support through NGOs. The government provides grant up to 30% of the project cost as appraised by lending institutions, while the remaining amount is provided by lending institutions as loan.'
    },
    {
        id: 'nstfdc',
        name: 'National SC/ST Hub - Term Loan Scheme',
        description: 'Subsidized loans for SC/ST entrepreneurs',
        eligibility: 'SC/ST owned MSMEs registered with Udyam',
        benefits: 'Subsidy up to ₹15 lakh on term loans for business expansion',
        documents: 'Caste certificate, Udyam registration, Business proof, Project report',
        deadline: 'March 2025',
        link: 'https://scsthub.in/',
        guide: '<ol><li>Register on SC/ST Hub portal</li><li>Identify eligible business expansion project</li><li>Approach designated lending institutions</li><li>Submit application with project report</li><li>Avail subsidy after loan disbursement</li></ol>',
        sector: 'All',
        businessType: ['SCST'],
        size: ['Micro', 'Small', 'Medium'],
        location: ['Delhi', 'Rural', 'Urban'],
        revenue: ['Low', 'Medium', 'High'],
        years: ['1-3', '3-5', '5+'],
        detailedDescription: 'The National SC/ST Hub provides subsidy support to SC/ST entrepreneurs for business expansion through term loans. The scheme provides subsidy up to ₹15 lakh or 15% of the project cost (whichever is lower) to reduce the financial burden on SC/ST entrepreneurs.'
    },
    {
        id: 'solarpump',
        name: 'PM-KUSUM Solar Pump Scheme',
        description: 'Subsidy for solar agricultural pumps',
        eligibility: 'Farmers with grid-connected agriculture pumps',
        benefits: '60-90% subsidy on solar pumps based on capacity',
        documents: 'Aadhaar, Land records, Electricity bill, Bank details',
        deadline: 'March 2026',
        link: 'https://pmkusum.mnre.gov.in/',
        guide: '<ol><li>Apply through your State Nodal Agency (SNAs) portal</li><li>Submit required documents</li><li>Get technical feasibility checked</li><li>Select from empaneled vendors</li><li>Get installation and claim subsidy</li></ol>',
        sector: 'Agriculture',
        businessType: ['Agri'],
        size: ['Micro', 'Small'],
        location: ['Rural'],
        revenue: ['Low', 'Medium'],
        years: ['1-3', '3-5', '5+'],
        detailedDescription: 'PM-KUSUM (Pradhan Mantri Kisan Urja Suraksha evam Utthaan Mahabhiyan) aims to add solar capacity of 30.8 GW by 2022 with total central financial support of ₹34,422 crore. The scheme provides 60-90% subsidy to farmers for installation of solar pumps and grid-connected solar power plants.'
    }
];

// Histogram data for about section
const histogramData = {
    labels: ['Low (0-40%)', 'Moderate (41-80%)', 'High (81-100%)'],
    datasets: [{
        label: 'Agri-MSMEs Dependency on Middlemen',
        data: [70, 790, 310],
        backgroundColor: [
            'rgba(30, 136, 229, 0.8)',
            'rgba(67, 160, 71, 0.8)',
            'rgba(239, 83, 80, 0.8)'
        ],
        borderColor: [
            'rgba(30, 136, 229, 1)',
            'rgba(67, 160, 71, 1)',
            'rgba(239, 83, 80, 1)'
        ],
        borderWidth: 1
    }]
};